### ISSUE TITLE
Получение алкоголя

### ISSUE THREAD

**Issue by KotikeD** [Morph-life/Potions-lesson#5]
Не совсем понятно: а как получать этот самый алкоголь? Вроде бы все на нем завязано!

**Comment by KotikeD0staff** [comment]
Пока что это работает только если оператор сервера выдаст вам его через инвентарь или по команде. Если в одиночном режиме на выживании, то нельзя. В следующей версии мы сделаем крафт из досок и камня. Блок воды будет крафтится из восьми ведер воды по краям и 1 алкоголю внутри! Ожидайте! #7 , там это будет. Пока!
